# Remove "version" if Docker Compose warns that it's obsolete

services:
  backend:
    build:
      context: . # The current directory is the build context
      dockerfile: Dockerfile # Name of your Dockerfile in the root
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pico_placa_db
      - SPRING_DATASOURCE_USERNAME=pico_user
      - SPRING_DATASOURCE_PASSWORD=cristi@nTe??o
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/pico-placa-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # 80 in the container (Nginx) mapped to 3000 on the host

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=pico_placa_db
      - POSTGRES_USER=pico_user
      - POSTGRES_PASSWORD=cristi@nTe??o
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
